variable "env_id" {
  description = "Unique environment identifier (UUID, generated by the API). Doubles as the Terraform state key and is used to name/tag every per-environment resource."
  type        = string
}

variable "env_name" {
  description = "Human-readable environment name, e.g. 'my-feature'."
  type        = string
}

variable "team" {
  description = "Team slug (URL-safe, lowercase), used in resource names and tags."
  type        = string
}

variable "env_type" {
  description = "Environment type: dev or staging."
  type        = string

  validation {
    condition     = contains(["dev", "staging"], var.env_type)
    error_message = "env_type must be exactly \"dev\" or \"staging\"."
  }
}

variable "ttl_hours" {
  description = "Time-to-live in hours. Not enforced by Terraform itself -- stored as a tag for cost governance and traceability; actual expiry is enforced by the API + TTL cron."
  type        = number
}

variable "region" {
  description = "AWS region to provision resources in."
  type        = string
  default     = "us-east-1"
}

variable "vpc_id" {
  description = "ID of the pre-existing shared VPC. Created once during the manual bootstrap step (Section 2.1) -- not managed by this configuration."
  type        = string
}

variable "container_image" {
  description = "Container image to deploy. Defaults to nginx for demo purposes; a real service image can be passed in later phases."
  type        = string
  default     = "public.ecr.aws/nginx/nginx:latest"
}
