"""
Runbook Generation Service

NOTE — pulled forward from Phase 5, same rationale as services/cost.py: the
Phase 4 callback handler's RUNNING branch has to generate a runbook the
moment Terraform outputs arrive, so this needs to exist now. The template
content matches Phase 5.3 in the implementation plan exactly — nothing here
is a placeholder, it's the real template, just built one phase early.

`generate()` is called with `env` still attached to the SQLAlchemy session
that's mid-transaction in the callback handler, so `env.team.name` and
`env.creator.username` lazy-load through existing relationships rather than
needing to be passed in separately.
"""

from __future__ import annotations

from datetime import datetime, timezone

from jinja2 import Template

RUNBOOK_TEMPLATE = """\
# Environment Runbook — {{ env.name }}

**Generated:** {{ now }}  |  **Expires:** {{ env.expires_at.strftime('%Y-%m-%d %H:%M UTC') }}
**Environment ID:** `{{ env.id }}`  |  **Type:** {{ env.env_type }}  |  **Region:** {{ env.aws_region }}
**Team:** {{ env.team.name }}  |  **Created by:** {{ env.creator.username }}

---

## Resource Summary

| Resource | Value |
|---|---|
| ECS Service | `{{ outputs.get('ecs_service_arn', 'n/a') }}` |
| ECS Cluster | `{{ outputs.get('ecs_cluster_arn', 'n/a') }}` |
| RDS Endpoint | `{{ outputs.get('rds_endpoint', 'n/a') }}` |
| Log Group | `{{ outputs.get('log_group_name', 'n/a') }}` |
| Subnet | `{{ outputs.get('subnet_id', 'n/a') }}` |
{% if outputs.get('service_url') %}| Service URL | `{{ outputs.get('service_url') }}` |
{% endif %}
---

## Connect to the Database

Credentials are in AWS Secrets Manager. Retrieve them:

```bash
aws secretsmanager get-secret-value \\
  --secret-id {{ outputs.get('rds_secret_arn', '<rds_secret_arn>') }} \\
  --query SecretString --output text | jq .
```

The secret contains: `host`, `port`, `dbname`, `username`, `password`, `url`.

---

## Tail Application Logs

```bash
aws logs tail {{ outputs.get('log_group_name', '<log_group_name>') }} --follow --region {{ env.aws_region }}
```

---

## Extend TTL

This environment expires at **{{ env.expires_at.strftime('%Y-%m-%d %H:%M UTC') }}**.

```bash
# CLI
idplite env extend {{ env.id }} --hours 24

# API
curl -X PATCH {{ api_base_url }}/environments/{{ env.id }}/ttl \\
  -H "X-API-Key: YOUR_KEY" -d '{"extend_hours": 24}'
```

---

## Destroy Early

```bash
idplite env destroy {{ env.id }}
```

---
*Auto-generated by IDP Lite on {{ now }}*
"""


def generate(env, outputs: dict, api_base_url: str = "http://localhost:8000") -> str:
    return Template(RUNBOOK_TEMPLATE).render(
        env=env,
        outputs=outputs or {},
        now=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        api_base_url=api_base_url,
    )